-- ============================================================================
-- キャスト slug 一括投入 + UNIQUE 制約変更
-- ============================================================================
-- 実行手順:
--   Supabase Dashboard → SQL Editor で全部ペーストして実行
--
-- 内容:
--   1. UNIQUE 制約を globally unique → (store_id, slug) の複合に変更
--   2. 自動変換できた 176件 に slug を投入
--
-- スキップ (10件、手動対応):
--   - store=1 id=15732 "ゲスト②" (gesuto重複)
--   - store=1 id=15754 "ねねa"  (nene重複)
--   - store=1 id=15834 "あまね"  (amane重複)
--   - store=2 id=15679 "相笠萌"  (漢字のみ)
--   - store=2 id=15695 "運命"    (漢字のみ)
--   - store=2 id=15698 "姫宮結愛" (漢字のみ)
--   - store=3 id=15639 "K"       (英字のみ)
--   - store=7 id=15763 "課長"    (漢字のみ)
--   - store=7 id=15794 "炭素"    (漢字のみ)
--   - store=7 id=15836 "ENTP"    (英字のみ)
-- ============================================================================

-- ---- 1. UNIQUE 制約変更 ----
ALTER TABLE casts DROP CONSTRAINT IF EXISTS casts_slug_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_casts_store_slug
  ON casts(store_id, slug)
  WHERE slug IS NOT NULL;

-- ---- 2. slug 一括投入 ----
BEGIN;
UPDATE casts SET slug = 'sumire' WHERE id = 15648;  -- store=1 "すみれ"
UPDATE casts SET slug = 'kanon' WHERE id = 15649;  -- store=1 "かのん"
UPDATE casts SET slug = 'kohaku' WHERE id = 15650;  -- store=1 "こはく"
UPDATE casts SET slug = 'chieru' WHERE id = 15651;  -- store=1 "ちえる"
UPDATE casts SET slug = 'nachan' WHERE id = 15652;  -- store=1 "なちゃん"
UPDATE casts SET slug = 'nodoka' WHERE id = 15653;  -- store=1 "のどか"
UPDATE casts SET slug = 'miyuu' WHERE id = 15654;  -- store=1 "みゆう"
UPDATE casts SET slug = 'yuyu' WHERE id = 15655;  -- store=1 "ゆゆ"
UPDATE casts SET slug = 'tantanmen' WHERE id = 15656;  -- store=1 "たんたんめん"
UPDATE casts SET slug = 'mimi' WHERE id = 15658;  -- store=1 "みみ"
UPDATE casts SET slug = 'moe' WHERE id = 15659;  -- store=1 "もえ"
UPDATE casts SET slug = 'hauru' WHERE id = 15660;  -- store=1 "はうる"
UPDATE casts SET slug = 'ginka' WHERE id = 15661;  -- store=1 "ぎんか"
UPDATE casts SET slug = 'tsuna' WHERE id = 15662;  -- store=1 "つな"
UPDATE casts SET slug = 'oimo' WHERE id = 15663;  -- store=1 "おいも"
UPDATE casts SET slug = 'chiru' WHERE id = 15666;  -- store=1 "ちる"
UPDATE casts SET slug = 'reiyuu' WHERE id = 15667;  -- store=1 "れいゆう"
UPDATE casts SET slug = 'nazuna' WHERE id = 15668;  -- store=1 "なずな"
UPDATE casts SET slug = 'nako' WHERE id = 15669;  -- store=1 "なこ"
UPDATE casts SET slug = 'ichizu' WHERE id = 15670;  -- store=1 "いちず"
UPDATE casts SET slug = 'gau' WHERE id = 15671;  -- store=1 "がう"
UPDATE casts SET slug = 'nekopi' WHERE id = 15672;  -- store=1 "ねこぴ"
UPDATE casts SET slug = 'inori' WHERE id = 15673;  -- store=1 "いのり"
UPDATE casts SET slug = 'ramu' WHERE id = 15674;  -- store=1 "白瀬らむ"
UPDATE casts SET slug = 'satoru' WHERE id = 15675;  -- store=1 "さとる"
UPDATE casts SET slug = 'masaya' WHERE id = 15676;  -- store=1 "まさや"
UPDATE casts SET slug = 'sari' WHERE id = 15677;  -- store=1 "さり"
UPDATE casts SET slug = 'shirabe' WHERE id = 15678;  -- store=1 "しらべ"
UPDATE casts SET slug = 'napi' WHERE id = 15706;  -- store=1 "なぴ"
UPDATE casts SET slug = 'shieru' WHERE id = 15707;  -- store=1 "しえる"
UPDATE casts SET slug = 'nene' WHERE id = 15708;  -- store=1 "ねね"
UPDATE casts SET slug = 'karuta' WHERE id = 15713;  -- store=1 "かるた"
UPDATE casts SET slug = 'mero' WHERE id = 15714;  -- store=1 "めろ"
UPDATE casts SET slug = 'chanu' WHERE id = 15716;  -- store=1 "ちゃぬ"
UPDATE casts SET slug = 'kurumi' WHERE id = 15717;  -- store=1 "くるみ"
UPDATE casts SET slug = 'furi' WHERE id = 15718;  -- store=1 "フリー"
UPDATE casts SET slug = 'gesuto' WHERE id = 15719;  -- store=1 "ゲスト①"
UPDATE casts SET slug = 'noa' WHERE id = 15722;  -- store=1 "のあ"
UPDATE casts SET slug = 'ribon' WHERE id = 15726;  -- store=1 "りぼん"
UPDATE casts SET slug = 'shio' WHERE id = 15727;  -- store=1 "しお"
UPDATE casts SET slug = 'mayoi' WHERE id = 15728;  -- store=1 "まよい"
UPDATE casts SET slug = 'kabocha' WHERE id = 15729;  -- store=1 "かぼちゃ"
UPDATE casts SET slug = 'sui' WHERE id = 15733;  -- store=1 "すい"
UPDATE casts SET slug = 'konoka' WHERE id = 15734;  -- store=1 "このか"
UPDATE casts SET slug = 'mao' WHERE id = 15736;  -- store=1 "まお"
UPDATE casts SET slug = 'amatsuka' WHERE id = 15737;  -- store=1 "あまつか"
UPDATE casts SET slug = 'yuki' WHERE id = 15738;  -- store=1 "ゆき"
UPDATE casts SET slug = 'ruuka' WHERE id = 15739;  -- store=1 "るうか"
UPDATE casts SET slug = 'ikura' WHERE id = 15740;  -- store=1 "いくら"
UPDATE casts SET slug = 'riiara' WHERE id = 15741;  -- store=1 "りぃあら"
UPDATE casts SET slug = 'yui' WHERE id = 15744;  -- store=1 "ゆい"
UPDATE casts SET slug = 'kuro' WHERE id = 15745;  -- store=1 "くろ"
UPDATE casts SET slug = 'yua' WHERE id = 15747;  -- store=1 "ゆあ"
UPDATE casts SET slug = 'mirua' WHERE id = 15748;  -- store=1 "みるあ"
UPDATE casts SET slug = 'umi' WHERE id = 15749;  -- store=1 "うみ"
UPDATE casts SET slug = 'uchan' WHERE id = 15751;  -- store=1 "うーちゃん"
UPDATE casts SET slug = 'rinne' WHERE id = 15752;  -- store=1 "りんね"
UPDATE casts SET slug = 'chan' WHERE id = 15753;  -- store=1 "飲酒ちゃん"
UPDATE casts SET slug = 'sachi' WHERE id = 15755;  -- store=1 "さち"
UPDATE casts SET slug = 'rara' WHERE id = 15761;  -- store=1 "らら"
UPDATE casts SET slug = 'ramune' WHERE id = 15762;  -- store=1 "星月らむね"
UPDATE casts SET slug = 'amane' WHERE id = 15775;  -- store=1 "あまね(旧)"
UPDATE casts SET slug = 'koa' WHERE id = 15776;  -- store=1 "こあ"
UPDATE casts SET slug = 'sana' WHERE id = 15806;  -- store=1 "さな"
UPDATE casts SET slug = 'kumori' WHERE id = 15809;  -- store=1 "くもり"
UPDATE casts SET slug = 'orino' WHERE id = 15810;  -- store=1 "おりの"
UPDATE casts SET slug = 'karen' WHERE id = 15821;  -- store=1 "かれん"
UPDATE casts SET slug = 'kana' WHERE id = 15680;  -- store=2 "かな"
UPDATE casts SET slug = 'rikopin' WHERE id = 15681;  -- store=2 "りこぴん"
UPDATE casts SET slug = 'yume' WHERE id = 15682;  -- store=2 "ゆめ"
UPDATE casts SET slug = 'tamau' WHERE id = 15683;  -- store=2 "たまう"
UPDATE casts SET slug = 'meru' WHERE id = 15684;  -- store=2 "甘猫める"
UPDATE casts SET slug = 'runa' WHERE id = 15685;  -- store=2 "るな"
UPDATE casts SET slug = 'momo' WHERE id = 15686;  -- store=2 "もも"
UPDATE casts SET slug = 'abi' WHERE id = 15687;  -- store=2 "あび"
UPDATE casts SET slug = 'hiyori' WHERE id = 15688;  -- store=2 "ひより"
UPDATE casts SET slug = 'kotsume' WHERE id = 15689;  -- store=2 "こつめ"
UPDATE casts SET slug = 'tsubasa' WHERE id = 15690;  -- store=2 "つばさ"
UPDATE casts SET slug = 'jiria' WHERE id = 15691;  -- store=2 "ぢゅりあ"
UPDATE casts SET slug = 'ayu' WHERE id = 15692;  -- store=2 "儚衣あゆ"
UPDATE casts SET slug = 'karen' WHERE id = 15694;  -- store=2 "かれん"
UPDATE casts SET slug = 'sano' WHERE id = 15696;  -- store=2 "さの"
UPDATE casts SET slug = 'mei' WHERE id = 15697;  -- store=2 "めい"
UPDATE casts SET slug = 'ria' WHERE id = 15699;  -- store=2 "りあ"
UPDATE casts SET slug = 'tamu' WHERE id = 15700;  -- store=2 "たむ"
UPDATE casts SET slug = 'nano' WHERE id = 15701;  -- store=2 "なの"
UPDATE casts SET slug = 'mikari' WHERE id = 15702;  -- store=2 "みかり"
UPDATE casts SET slug = 'kaito' WHERE id = 15710;  -- store=2 "かいと"
UPDATE casts SET slug = 'usshi' WHERE id = 15711;  -- store=2 "うっしー"
UPDATE casts SET slug = 'furi' WHERE id = 15715;  -- store=2 "フリー"
UPDATE casts SET slug = 'momoto' WHERE id = 15720;  -- store=2 "ももと"
UPDATE casts SET slug = 'asuka' WHERE id = 15724;  -- store=2 "あすか"
UPDATE casts SET slug = 'riu' WHERE id = 15725;  -- store=2 "りう"
UPDATE casts SET slug = 'nanase' WHERE id = 15730;  -- store=2 "ななせ"
UPDATE casts SET slug = 'miru' WHERE id = 15731;  -- store=2 "みる"
UPDATE casts SET slug = 'mizeru' WHERE id = 15735;  -- store=2 "みぜる"
UPDATE casts SET slug = 'chaso' WHERE id = 15742;  -- store=2 "ちゃそ"
UPDATE casts SET slug = 'riri' WHERE id = 15746;  -- store=2 "りり"
UPDATE casts SET slug = 'yuni' WHERE id = 15750;  -- store=2 "ゆに"
UPDATE casts SET slug = 'mirei' WHERE id = 15817;  -- store=2 "みれい"
UPDATE casts SET slug = 'satoru' WHERE id = 15818;  -- store=2 "さとる"
UPDATE casts SET slug = 'shirabe' WHERE id = 15819;  -- store=2 "しらべ"
UPDATE casts SET slug = 'shio' WHERE id = 15829;  -- store=2 "しお"
UPDATE casts SET slug = 'honamin' WHERE id = 15831;  -- store=2 "ほなみん"
UPDATE casts SET slug = 'souma' WHERE id = 15833;  -- store=2 "そうま"
UPDATE casts SET slug = 'nina' WHERE id = 15640;  -- store=3 "にな"
UPDATE casts SET slug = 'anri' WHERE id = 15641;  -- store=3 "あんり"
UPDATE casts SET slug = 'kaito' WHERE id = 15642;  -- store=3 "かいと"
UPDATE casts SET slug = 'furi' WHERE id = 15643;  -- store=3 "フリー"
UPDATE casts SET slug = 'eiji' WHERE id = 15645;  -- store=3 "えいじ"
UPDATE casts SET slug = 'yuigesuto' WHERE id = 15712;  -- store=3 "ゆい（ゲスト出勤）"
UPDATE casts SET slug = 'rizegesuto' WHERE id = 15723;  -- store=3 "りぜ（ゲスト出勤）"
UPDATE casts SET slug = 'chiharu' WHERE id = 15756;  -- store=7 "ちはる"
UPDATE casts SET slug = 'rei' WHERE id = 15757;  -- store=7 "レイ"
UPDATE casts SET slug = 'nemu' WHERE id = 15758;  -- store=7 "ねむ"
UPDATE casts SET slug = 'atashiacha' WHERE id = 15759;  -- store=7 "あたしあちゃ"
UPDATE casts SET slug = 'nene' WHERE id = 15760;  -- store=7 "萌乃ねね"
UPDATE casts SET slug = 'yua' WHERE id = 15764;  -- store=7 "姫乃ゆあ"
UPDATE casts SET slug = 'riri' WHERE id = 15765;  -- store=7 "りり"
UPDATE casts SET slug = 'yunya' WHERE id = 15766;  -- store=7 "ゆにゃ"
UPDATE casts SET slug = 'kirari' WHERE id = 15767;  -- store=7 "きらり"
UPDATE casts SET slug = 'romi' WHERE id = 15768;  -- store=7 "闇夜ろみ"
UPDATE casts SET slug = 'roze' WHERE id = 15769;  -- store=7 "ロゼ"
UPDATE casts SET slug = 'hina' WHERE id = 15770;  -- store=7 "紬ひな"
UPDATE casts SET slug = 'aya' WHERE id = 15771;  -- store=7 "あや"
UPDATE casts SET slug = 'ruki' WHERE id = 15772;  -- store=7 "るき"
UPDATE casts SET slug = 'misa' WHERE id = 15773;  -- store=7 "みさ"
UPDATE casts SET slug = 'nina' WHERE id = 15774;  -- store=7 "猫乃にな"
UPDATE casts SET slug = 'ui' WHERE id = 15777;  -- store=7 "ぅぃ"
UPDATE casts SET slug = 'miruku' WHERE id = 15778;  -- store=7 "みるく"
UPDATE casts SET slug = 'runa' WHERE id = 15779;  -- store=7 "るな"
UPDATE casts SET slug = 'amane' WHERE id = 15780;  -- store=7 "あまね"
UPDATE casts SET slug = 'mirua' WHERE id = 15781;  -- store=7 "みるあ"
UPDATE casts SET slug = 'iori' WHERE id = 15782;  -- store=7 "いおり"
UPDATE casts SET slug = 'nano' WHERE id = 15783;  -- store=7 "なの"
UPDATE casts SET slug = 'sora' WHERE id = 15784;  -- store=7 "そら"
UPDATE casts SET slug = 'rinne' WHERE id = 15785;  -- store=7 "りんね"
UPDATE casts SET slug = 'meanya' WHERE id = 15788;  -- store=7 "めあにゃ"
UPDATE casts SET slug = 'sakuma' WHERE id = 15789;  -- store=7 "さくま"
UPDATE casts SET slug = 'jun' WHERE id = 15790;  -- store=7 "ジュン"
UPDATE casts SET slug = 'amai' WHERE id = 15791;  -- store=7 "あまい"
UPDATE casts SET slug = 'raro' WHERE id = 15793;  -- store=7 "らろ"
UPDATE casts SET slug = 'ran' WHERE id = 15795;  -- store=7 "らん"
UPDATE casts SET slug = 'amiri' WHERE id = 15796;  -- store=7 "あみり"
UPDATE casts SET slug = 'meru' WHERE id = 15797;  -- store=7 "める"
UPDATE casts SET slug = 'koyoi' WHERE id = 15798;  -- store=7 "こよい"
UPDATE casts SET slug = 'miruki' WHERE id = 15799;  -- store=7 "みるき"
UPDATE casts SET slug = 'ami' WHERE id = 15800;  -- store=7 "あみ"
UPDATE casts SET slug = 'nekomi' WHERE id = 15801;  -- store=7 "ねこみ"
UPDATE casts SET slug = 'mio' WHERE id = 15802;  -- store=7 "みお"
UPDATE casts SET slug = 'hatsume' WHERE id = 15803;  -- store=7 "はつめ"
UPDATE casts SET slug = 'riachama' WHERE id = 15804;  -- store=7 "りあちゃま"
UPDATE casts SET slug = 'noa' WHERE id = 15805;  -- store=7 "のあ"
UPDATE casts SET slug = 'tsukasa' WHERE id = 15807;  -- store=7 "つかさ"
UPDATE casts SET slug = 'koa' WHERE id = 15808;  -- store=7 "こあ"
UPDATE casts SET slug = 'moa' WHERE id = 15811;  -- store=7 "もあ"
UPDATE casts SET slug = 'uru' WHERE id = 15812;  -- store=7 "うる"
UPDATE casts SET slug = 'yuragi' WHERE id = 15813;  -- store=7 "ゆらぎ"
UPDATE casts SET slug = 'miko' WHERE id = 15814;  -- store=7 "みこ"
UPDATE casts SET slug = 'kuromiya' WHERE id = 15815;  -- store=7 "くろみや"
UPDATE casts SET slug = 'kakeru' WHERE id = 15816;  -- store=7 "かける"
UPDATE casts SET slug = 'toa' WHERE id = 15820;  -- store=7 "犬愛とあ"
UPDATE casts SET slug = 'miina' WHERE id = 15822;  -- store=7 "みいな"
UPDATE casts SET slug = 'furi' WHERE id = 15823;  -- store=7 "フリー"
UPDATE casts SET slug = 'momoto' WHERE id = 15824;  -- store=7 "ももと"
UPDATE casts SET slug = 'ayato' WHERE id = 15825;  -- store=7 "あやと"
UPDATE casts SET slug = 'rumina' WHERE id = 15826;  -- store=7 "るみな"
UPDATE casts SET slug = 'satoru' WHERE id = 15827;  -- store=7 "さとる"
UPDATE casts SET slug = 'fuwari' WHERE id = 15828;  -- store=7 "ふわり"
UPDATE casts SET slug = 'gesuto' WHERE id = 15830;  -- store=7 "ゲスト"
UPDATE casts SET slug = 'teira' WHERE id = 15832;  -- store=7 "てぃら"
UPDATE casts SET slug = 'ichigonya' WHERE id = 15835;  -- store=7 "いちごにゃ"
UPDATE casts SET slug = 'yowai' WHERE id = 15838;  -- store=7 "よわい"
UPDATE casts SET slug = 'tsukino' WHERE id = 15839;  -- store=7 "ツキノ"
UPDATE casts SET slug = 'pomu' WHERE id = 15840;  -- store=7 "ぽむ"
UPDATE casts SET slug = 'mayoi' WHERE id = 15841;  -- store=7 "まよい"
COMMIT;
